apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
        - args:
            - python
            - manage.py
            - run
            - -h
            - 0.0.0.0
            - -p
            - "5001"
          env:
            - name: APP_SETTINGS
              value: project.server.config.DevelopmentConfig
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://redis:6379/0
            - name: FLASK_DEBUG
              value: "1"
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: PORT
              value: "5001"
          image: api
          name: api
          resources: {}
      restartPolicy: Always
status: {}
