apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: API_PORT
              value: "5001"
            - name: API_URL
              value: http://api
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://redis:6379/0
            - name: FLASK_DEBUG
              value: "1"
            - name: MONGODB_URI
              value: mongodb://mongodb:27017
            - name: PORT
              value: "5000"
          image: backend
          name: backend
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
